### ISSUE TITLE
Pagination example appears broken

### ISSUE THREAD

**Issue by ee0pdt** [tannerlinsley/react-query#227]
### Running the paginatation example gives error message

**Repro steps:**

1. clone repo
2. npm install
3. npm run dev
4. load http://localhost:3000 in browser

**Expected Outcome:**

App loads

**Actual Outcome:**

Get following error message:

```
The default export is not a React Component in page: "/"
Error: The default export is not a React Component in page: "/"
    at Object.renderToHTML (/Users/pete/Documents/react-query/examples/pagination/node_modules/next/dist/next-server/server/render.js:181:19)
    at DevServer.renderToHTMLWithComponents (/Users/pete/Documents/react-query/examples/pagination/node_modules/next/dist/next-server/server/next-server.js:597:29)
    at DevServer.renderToHTML (/Users/pete/Documents/react-query/examples/pagination/node_modules/next/dist/next-server/server/next-server.js:703:35)
    at async DevServer.renderToHTML (/Users/pete/Documents/react-query/examples/pagination/node_modules/next/dist/server/next-dev-server.js:15:582)
    at async DevServer.render (/Users/pete/Documents/react-query/examples/pagination/node_modules/next/dist/next-server/server/next-server.js:502:22)
    at async Object.fn (/Users/pete/Documents/react-query/examples/pagination/node_modules/next/dist/next-server/server/next-server.js:360:17)
    at async Router.execute (/Users/pete/Documents/react-query/examples/pagination/node_modules/next/dist/next-server/server/router.js:117:32)
    at async DevServer.run (/Users/pete/Documents/react-query/examples/pagination/node_modules/next/dist/next-server/server/next-server.js:475:29)
    at async DevServer.handleRequest (/Users/pete/Documents/react-query/examples/pagination/node_modules/next/dist/next-server/server/next-server.js:131:20)
```

**Comment by cherniavskii** [comment]
Yeah, that example needs to be fixed.
Wanna submit a PR?

**Comment by sigfriedCub1990** [comment]
Can I take this @cherniavskii ?

**Comment by cherniavskii** [comment]
Sure, go ahead
