### ISSUE TITLE
Tests inconsistently and occasionally fail when run in CI environments

### ISSUE THREAD

**Issue by wolverineks** [tannerlinsley/react-query#751]
**Describe the bug**
occasional warnings and failures

**To Reproduce**
run the test suite a bunch of times

**Expected behavior**
tests pass every timee

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by wolverineks** [comment]
```bash
 FAIL  src/react/tests/useQuery.test.js
  ● useQuery › should reset failureCount on successful fetch

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 1
    Received number of calls: 0

      365 | 
      366 |     expect(prefetchQueryFn).toHaveBeenCalledTimes(1)
    > 367 |     expect(queryFn).toHaveBeenCalledTimes(1)
          |                     ^
      368 |   })
      369 | 
      370 |   it('should not refetch if not stale after a prefetch', async () => {

      at src/react/tests/useQuery.test.js:367:21
```

**Comment by wolverineks** [comment]
```bash
 FAIL  src/react/tests/useQuery.test.js
  ● useQuery › should reset failureCount on successful fetch

    TestingLibraryElementError: Unable to find an element with the text: data. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

    <body>
      <div>
        <div>
          <div>
            failureCount 
            2
          </div>
        </div>
      </div>
      <div>
        <div>
          <div />
        </div>
      </div>
      <div>
        <div>
          <div />
        </div>
      </div>
    </body>

    <html>
      <head />
      <body>
        <div>
          <div>
            <div>
              failureCount 
              2
            </div>
          </div>
        </div>
        <div>
          <div>
            <div />
          </div>
        </div>
        <div>
          <div>
            <div />
          </div>
        </div>
      </body>
    </html>Error: Unable to find an element with the text: data. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

    <body>
      <div>
        <div>
          <div>
            failureCount 
            2
          </div>
        </div>
      </div>
      <div>
        <div>
          <div />
        </div>
      </div>
      <div>
        <div>
          <div />
        </div>
      </div>
    </body>

      393 |     const rendered = render(<Page />)
      394 | 
    > 395 |     await waitFor(() => rendered.getByText('data'))
          |           ^
      396 | 
      397 |     expect(prefetchQueryFn).toHaveBeenCalledTimes(1)
      398 |     expect(queryFn).toHaveBeenCalledTimes(0)

      at waitForWrapper (node_modules/@testing-library/dom/dist/wait-for.js:134:27)
      at src/react/tests/useQuery.test.js:395:11
      at node_modules/react-dom/cjs/react-dom-test-utils.development.js:961:13

  ● useQuery › should use prefetched data for dependent query

    TestingLibraryElementError: Unable to find an element with the text: failureCount 0. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

    <body>
      <div>
        <div>
          <button>
            setKey
          </button>
          <div />
        </div>
      </div>
    </body>

    <html>
      <head />
      <body>
        <div>
          <div>
            <button>
              setKey
            </button>
            <div />
          </div>
        </div>
      </body>
    </html>Error: Unable to find an element with the text: failureCount 0. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

    <body>
      <div>
        <div>
          <button>
            setKey
          </button>
          <div />
        </div>
      </div>
    </body>

      430 | 
      431 |     await waitFor(() => rendered.getByText('failureCount 2'))
    > 432 |     await waitFor(() => rendered.getByText('failureCount 0'))
          |           ^
      433 | 
      434 |     console.error.mockRestore()
      435 |   })

      at waitForWrapper (node_modules/@testing-library/dom/dist/wait-for.js:134:27)
      at src/react/tests/useQuery.test.js:432:11

  ● useQuery › should use prefetched data for dependent query

    TestingLibraryElementError: Unable to find an element with the text: data. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

    <body />

    <html>
      <head />
      <body />
    </html>Error: Unable to find an element with the text: data. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

    <body />

      362 |     const rendered = render(<Page />)
      363 | 
    > 364 |     await waitFor(() => rendered.getByText('data'))
          |           ^
      365 | 
      366 |     expect(prefetchQueryFn).toHaveBeenCalledTimes(1)
      367 |     expect(queryFn).toHaveBeenCalledTimes(1)

      at waitForWrapper (node_modules/@testing-library/dom/dist/wait-for.js:134:27)
      at src/react/tests/useQuery.test.js:364:11
      at node_modules/react-dom/cjs/react-dom-test-utils.development.js:961:13
```

**Comment by wolverineks** [comment]
```bash
 PASS  src/react/tests/useInfiniteQuery.test.js
  ● Console

    console.error
      Warning: You seem to have overlapping act() calls, this is not supported. Be sure to await previous act() calls before making a new one. 

      at printWarning (node_modules/react-dom/cjs/react-dom-test-utils.development.js:87:30)
      at error (node_modules/react-dom/cjs/react-dom-test-utils.development.js:59:5)
      at onDone (node_modules/react-dom/cjs/react-dom-test-utils.development.js:921:9)
      at node_modules/react-dom/cjs/react-dom-test-utils.development.js:960:13
```

**Comment by wolverineks** [comment]
```bash
 FAIL  src/react/tests/useQuery.test.js
  ● useQuery › should reset failureCount on successful fetch

    TestingLibraryElementError: Unable to find an element with the text: data. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

    <body>
      <div>
        <div>
          <div>
            failureCount 
            2
          </div>
        </div>
      </div>
      <div>
        <div>
          <div />
        </div>
      </div>
      <div>
        <div>
          <div />
        </div>
      </div>
    </body>

    <html>
      <head />
      <body>
        <div>
          <div>
            <div>
              failureCount 
              2
            </div>
          </div>
        </div>
        <div>
          <div>
            <div />
          </div>
        </div>
        <div>
          <div>
            <div />
          </div>
        </div>
      </body>
    </html>Error: Unable to find an element with the text: data. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

    <body>
      <div>
        <div>
          <div>
            failureCount 
            2
          </div>
        </div>
      </div>
      <div>
        <div>
          <div />
        </div>
      </div>
      <div>
        <div>
          <div />
        </div>
      </div>
    </body>

      393 |     const rendered = render(<Page />)
      394 | 
    > 395 |     await waitFor(() => rendered.getByText('data'))
          |           ^
      396 | 
      397 |     expect(prefetchQueryFn).toHaveBeenCalledTimes(1)
      398 |     expect(queryFn).toHaveBeenCalledTimes(0)

      at waitForWrapper (node_modules/@testing-library/dom/dist/wait-for.js:134:27)
      at src/react/tests/useQuery.test.js:395:11
      at node_modules/react-dom/cjs/react-dom-test-utils.development.js:961:13
```

**Comment by wolverineks** [comment]
```bash
 ● useQuery › should use prefetched data for dependent query

    TestingLibraryElementError: Unable to find an element with the text: failureCount 0. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

    <body>
      <div>
        <div>
          <button>
            setKey
          </button>
          <div />
        </div>
      </div>
    </body>

    <html>
      <head />
      <body>
        <div>
          <div>
            <button>
              setKey
            </button>
            <div />
          </div>
        </div>
      </body>
    </html>Error: Unable to find an element with the text: failureCount 0. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

    <body>
      <div>
        <div>
          <button>
            setKey
          </button>
          <div />
        </div>
      </div>
    </body>

      430 | 
      431 |     await waitFor(() => rendered.getByText('failureCount 2'))
    > 432 |     await waitFor(() => rendered.getByText('failureCount 0'))
          |           ^
      433 | 
      434 |     console.error.mockRestore()
      435 |   })

      at waitForWrapper (node_modules/@testing-library/dom/dist/wait-for.js:134:27)
      at src/react/tests/useQuery.test.js:432:11
```

**Comment by wolverineks** [comment]
```bash
  ● useQuery › should support dependent queries via the enable config option

    TestingLibraryElementError: Unable to find an element with the text: data. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

    <body>
      <div>
        <div>
          <div>
            Status: 
            idle
          </div>
          <h2>
            Data: 
            no data
          </h2>
          <button>
            fetch
          </button>
        </div>
      </div>
    </body>

    <html>
      <head />
      <body>
        <div>
          <div>
            <div>
              Status: 
              idle
            </div>
            <h2>
              Data: 
              no data
            </h2>
            <button>
              fetch
            </button>
          </div>
        </div>
      </body>
    </html>Error: Unable to find an element with the text: data. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

    <body>
      <div>
        <div>
          <div>
            Status: 
            idle
          </div>
          <h2>
            Data: 
            no data
          </h2>
          <button>
            fetch
          </button>
        </div>
      </div>
    </body>

      362 |     const rendered = render(<Page />)
      363 | 
    > 364 |     await waitFor(() => rendered.getByText('data'))
          |           ^
      365 | 
      366 |     expect(prefetchQueryFn).toHaveBeenCalledTimes(1)
      367 |     expect(queryFn).toHaveBeenCalledTimes(1)

      at waitForWrapper (node_modules/@testing-library/dom/dist/wait-for.js:134:27)
      at src/react/tests/useQuery.test.js:364:11
      at node_modules/react-dom/cjs/react-dom-test-utils.development.js:961:13
```

**Comment by wolverineks** [comment]
```bash
  ● useQuery › should update data upon interval changes

    TestingLibraryElementError: Unable to find an element with the text: Status: loading. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

    <body>
      <div>
        <div>
          count: 
          4
        </div>
      </div>
    </body>

    <html>
      <head />
      <body>
        <div>
          <div>
            count: 
            4
          </div>
        </div>
      </body>
    </html>Error: Unable to find an element with the text: Status: loading. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

    <body>
      <div>
        <div>
          count: 
          4
        </div>
      </div>
    </body>

      497 |     fireEvent.click(rendered.getByText('fetch'))
      498 | 
    > 499 |     await waitFor(() => rendered.getByText('Status: loading'))
          |           ^
      500 |     await waitFor(() => [
      501 |       rendered.getByText('Status: success'),
      502 |       rendered.getByText('Data: data'),

      at waitForWrapper (node_modules/@testing-library/dom/dist/wait-for.js:134:27)
      at Object.apply (src/react/tests/useQuery.test.js:499:11)
      at Object.<anonymous> (src/react/tests/useQuery.test.js:77:29)
```

**Comment by tannerlinsley** [comment]
Yeah, I've been battling this for a while. It has something to do with the timers under conflicting with each other and causing random failures. When tested in isolation, each one of the tests should be passing on its own.

**Comment by wolverineks** [comment]
```bash
 PASS  src/react/tests/useInfiniteQuery.test.js (5.558 s)
  ● Console

    console.error
      Warning: You seem to have overlapping act() calls, this is not supported. Be sure to await previous act() calls before making a new one. 

      at printWarning (node_modules/react-dom/cjs/react-dom-test-utils.development.js:87:30)
      at error (node_modules/react-dom/cjs/react-dom-test-utils.development.js:59:5)
      at onDone (node_modules/react-dom/cjs/react-dom-test-utils.development.js:921:9)
      at node_modules/react-dom/cjs/react-dom-test-utils.development.js:968:13
      at Immediate._onImmediate (node_modules/react-dom/cjs/react-dom-test-utils.development.js:890:9)

    console.error
      Warning: You seem to have overlapping act() calls, this is not supported. Be sure to await previous act() calls before making a new one. 

      at printWarning (node_modules/react-dom/cjs/react-dom-test-utils.development.js:87:30)
      at error (node_modules/react-dom/cjs/react-dom-test-utils.development.js:59:5)
      at onDone (node_modules/react-dom/cjs/react-dom-test-utils.development.js:921:9)
      at node_modules/react-dom/cjs/react-dom-test-utils.development.js:960:13

    console.error
      Warning: You seem to have overlapping act() calls, this is not supported. Be sure to await previous act() calls before making a new one. 

      at printWarning (node_modules/react-dom/cjs/react-dom-test-utils.development.js:87:30)
      at error (node_modules/react-dom/cjs/react-dom-test-utils.development.js:59:5)
      at onDone (node_modules/react-dom/cjs/react-dom-test-utils.development.js:921:9)
      at node_modules/react-dom/cjs/react-dom-test-utils.development.js:960:13

    console.error
      Warning: You seem to have overlapping act() calls, this is not supported. Be sure to await previous act() calls before making a new one. 

      at printWarning (node_modules/react-dom/cjs/react-dom-test-utils.development.js:87:30)
      at error (node_modules/react-dom/cjs/react-dom-test-utils.development.js:59:5)
      at onDone (node_modules/react-dom/cjs/react-dom-test-utils.development.js:921:9)
      at node_modules/react-dom/cjs/react-dom-test-utils.development.js:960:13

    console.error
      Warning: You seem to have overlapping act() calls, this is not supported. Be sure to await previous act() calls before making a new one. 

      at printWarning (node_modules/react-dom/cjs/react-dom-test-utils.development.js:87:30)
      at error (node_modules/react-dom/cjs/react-dom-test-utils.development.js:59:5)
      at onDone (node_modules/react-dom/cjs/react-dom-test-utils.development.js:921:9)
      at node_modules/react-dom/cjs/react-dom-test-utils.development.js:960:13

    console.error
      Warning: You seem to have overlapping act() calls, this is not supported. Be sure to await previous act() calls before making a new one. 

      at printWarning (node_modules/react-dom/cjs/react-dom-test-utils.development.js:87:30)
      at error (node_modules/react-dom/cjs/react-dom-test-utils.development.js:59:5)
      at onDone (node_modules/react-dom/cjs/react-dom-test-utils.development.js:921:9)
      at node_modules/react-dom/cjs/react-dom-test-utils.development.js:960:13

    console.error
      Warning: You seem to have overlapping act() calls, this is not supported. Be sure to await previous act() calls before making a new one. 

      at printWarning (node_modules/react-dom/cjs/react-dom-test-utils.development.js:87:30)
      at error (node_modules/react-dom/cjs/react-dom-test-utils.development.js:59:5)
      at onDone (node_modules/react-dom/cjs/react-dom-test-utils.development.js:921:9)
      at node_modules/react-dom/cjs/react-dom-test-utils.development.js:960:13

    console.error
      Warning: You seem to have overlapping act() calls, this is not supported. Be sure to await previous act() calls before making a new one. 

      at printWarning (node_modules/react-dom/cjs/react-dom-test-utils.development.js:87:30)
      at error (node_modules/react-dom/cjs/react-dom-test-utils.development.js:59:5)
      at onDone (node_modules/react-dom/cjs/react-dom-test-utils.development.js:921:9)
      at node_modules/react-dom/cjs/react-dom-test-utils.development.js:960:13
```

**Comment by wolverineks** [comment]
```bash
● useQuery › should not mark query as fetching, when using initialData

    expect(jest.fn()).toHaveBeenCalledTimes(expected)

    Expected number of calls: 1
    Received number of calls: 0

      365 | 
      366 |     expect(prefetchQueryFn).toHaveBeenCalledTimes(1)
    > 367 |     expect(queryFn).toHaveBeenCalledTimes(1)
          |                     ^
      368 |   })
      369 | 
      370 |   it('should not refetch if not stale after a prefetch', async () => {

      at src/react/tests/useQuery.test.js:367:21
```

**Comment by kamranayub** [comment]
I noticed there's no test setup globally for clearing the global cache:

```js
afterEach(() => {
  // clear global cache
  act(() => queryCache.clear());
});
```

Not sure if that's as useful for the lib itself. There may also be missing `act`s I would guess too.

**Comment by tannerlinsley** [comment]
Tests seem to be passing more consistently now. Things will get better as we nail down the edge case act warnings etc. They all pass locally with 100% consistency when run serially, and that's good enough for me.
